name: weather_app
packages: 
  - modules/**
  - '*'

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  test:selective_unit_test:
    run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test
  test:
    run: melos run test:selective_unit_test --no-select
    description: Run all Flutter tests in this project.

  analyze:
    run: melos exec -- flutter analyze .
    description: Run `dart analyze` in all packages.

  test_result:selective_test_result:
    run: melos exec --dir-exists="test" --fail-fast -- flutter test --machine | tojunit
    description: Run `flutter test --machine | tojunit` in all packages.
    select-package:
      flutter: true
      dir-exists: test
  test_results:
    run: melos run test_result:selective_test_result --no-select
    description: Run all flutter test --machine | tojunitin this project.
  

  gen_coverage: melos exec -- "\$MELOS_ROOT_PATH/combine_coverage.sh"