name: weather_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.7
  flutter_screenutil: ^5.3.1
  responsive_framework: ^0.1.9

  melos: ^3.0.0

  cupertino_icons: ^1.0.2

  # RESPONSE
  dartz: ^0.10.1

  # LAYOUT
  after_layout: ^1.1.0

  #NEWTWORK CALLS
  dio: ^4.0.6

  # LOGGER
  pretty_dio_logger: ^1.1.1
  fimber: ^0.6.1

  # INTERNATIONALIZATION
  easy_localization: ^3.0.0

  # STATE MANAGEMENT
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  bloc_test: ^9.0.3
  mockito: ^5.3.2 

  # LOCATION
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  permission_handler: ^8.2.5
  
  # liquid_pull_to_refresh: ^3.0.1
  
  # GENERATOR
  freezed_annotation:

  date_time_format: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2

  injectable_generator:
  build_runner:
  freezed:
  flutter_lints: ^1.0.0 
  dart_code_metrics: ^5.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
