// Mocks generated by Mockito 5.3.2 from annotations
// in weather_app/test/core/repository/current_weather_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/core/bloc/currentWeatherCubit/data/weather_info_model.dart'
    as _i2;

import 'current_weather_repository_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWeatherInfoModel_0 extends _i1.SmartFake
    implements _i2.WeatherInfoModel {
  _FakeWeatherInfoModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CurrentWeatherRepositoryTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrentWeatherRepositoryTest extends _i1.Mock
    implements _i3.CurrentWeatherRepositoryTest {
  MockCurrentWeatherRepositoryTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WeatherInfoModel> getCurrentLocationWeather(
          Map<String, dynamic>? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocationWeather,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.WeatherInfoModel>.value(_FakeWeatherInfoModel_0(
          this,
          Invocation.method(
            #getCurrentLocationWeather,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.WeatherInfoModel>);
}
